FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8

WORKDIR /inetpub/wwwroot

COPY /Publish/. ./

# docker build -t iis-app .
# docker run --rm --name iis-app -d -p 9990:80 iis-app
# docker stop iis-app
